services:
  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dido@1234
      POSTGRES_DB: levannel_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    env_file:
      - .env.production

    depends_on:
      - postgres

volumes:
  postgres_data: