name: Levannel API CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer dépendances
        run: npm install

      - name: Build
        run: npm run build